In [1]:
##Ensemble Methods
##Ensemble methods is a machine learning paradigm where multiple model(often called weak learners) are trained to solve
##the same problem and combined to get better results.
##The main hypothesis is that when weak models are correctly combined we can obtain a more accurate and robust models

##Single weak learner
##In machine learning,no matter if we are facing a classification or regression problem,the chioce of model is extremely
##important to have any chance to obtain good results.This choice can depend on many variables of the problem:
##quantity of data
##dimensionality of the space
##distribution hypothesis

##A low bias and a low variance, although they most often vary in opposite directions,are the two most important fundamental
##features expected for a model

In [1]:
##Ensemble Methods
##Divide entire dataset into subset
##we will apply model which will learn subset...5 model for 5 subset
##model trained on some data of subset
##suppose 200 column so divide into 50 column..so easy to grasp 50 columns at a time
##Now we will average the output of all the models
##this technique known as emsemble technique meaning unity or collection.
##if we have huge dataset then to grasp it easily we cna use the ensemble technique
##We can apply different decisiontree classifier for different subset
##When we use emsemble technique then decision tree classifier will be used
##Emsemble Methods two category..Bagging and Boosting



In [1]:
##Bagging
##Entire dataset divided into chunks of dataset
##and different decisiontree model will be used for each subset..then we take the mean ..so accuracy mean
##Bagging is parallel model or bootstrap aggregation

##Boosting is sequential model....one of dataset is learnt by one of  the model after model learning
##output of previous model will be given as input in second model..so accuracy will be boosted
##so it is a sequence...accuracy of later model will be better and boosted.

##In Bagging ..we have random forest algorithm ,is that ensemble method that will assist in bagging
##forest so lot of trees..single tree(decision tree)..many no. of decision tree

##In sequential methods..we have adaboost.. n other is gradient boosting..(present in sklearn)
##other algorithm in boosting..is xgboost and catboost ....(not present in sklearn)
##we have to install xgboost n catboost seperatly..! pip install Xgboost....from Xgboost import XgboostClassifier
##same with catboost....! pip install catboost

##All the algorithm...random forest,adaboost and gradient boost..have classifier and regressor

##Sklearn.ensemble module includes two averaging algorithms based on randomized decision tree..the random forest algorithm and 
##the extra tree method (on very large dataset it is applied).Both algorihm are perturb and combine techniques specially designed for trees.
##Diverse set of classifier is created by introducing randomness in the classifier construction
##the prediction of the ensemble is given as the averaged prediction of the individual classifiers.

##The Random Forest is a meta estimator that fits a number of decision tree classifiers on various sub samples of the dataset.
##and uses averaging to improve the prediction accuracy and control over fitting.The sub sample size is controlled by max_samples parameter
##if bootstrap=True(default),otherwise whole dataset is used to build each tree

##n_estimators=100(default)....no of trees in the forest
##criterion:{"gini,"entropy}..default="gini"

##We have RandomForestRegressor as well


In [2]:
##Adaboost..core principal is to fit a sequence of weak learner(i.e. models thata re slightly better than random guessing such as
##decision trees) on repeatedly modified version of data.The prediction from all of them are then combined through a weighted majority vote
##or sum to produce the final prediction.

##Models are dependent in XGboostwhile in Adaboost tries to add old models that do well when previous models  pass

##The data modification at so called boosting iteration consist of applying weights..w1,w2,..wn..to each of the training samples
##those weights are all set to  w1=1/N so the first step simply trains a weak learner on the original data.
##For each successive iteration,the sample weights are individually modified and the learning algorithm is reapplied to the
##reweighted data.

##At a given step,those training exmaples that were incorrectly predicted by the boosted model induced at the precious step have
##their weight increased for those that were predicted correctly.
##As the iterations proceed examples that are difficult  to predict receive ever incresing influence.
##Each subsequent weak learner is thereby  forced to concentrate on the examples that are missed by the previous ones in the
##sequence

##base_estimator (Decision tree Classifier by default)..can be changed
##n_estimators (default is 50)


##Ensemble is acomposite model combines a series of low performing classifier with an aim of creating a improved classifier
##Here,indiviual classifier vote and final prediction label return that performs majority voting.
##Ensemble offer more accuracy than individual or base classifier.

##Ensemble method can be parallel by allocating each base learner  to different different machines
##finally you can say that emsemble learning methods are meta algorithms that combine several machine leanring method into a 
##single predictive method to increase performance.

##Bagging reduce the variance..boosting reduce the bias and stacking improve the predcition..Stacking are caled blending.


In [3]:
##Bagging--combine multiple learner in a way to reduce the variance of estimates.For example..random forest trains
##M decision tree.You can train M  different trees on  different  random subsets of the data and perform voting for final prediction.
##Bagging ensemble method are RandomForest and ExtraTrees

##Boosting,,are a set of low accurate classifier to create higher accurate classifier.low accuracy classifier offer better accuracy
##then the flipping of a coin.High accurate classifier(strogn classifier) offer error rate close to 0.Boosting algorithm can 
##track the model who failed teh acurate prediction.Boosting algo are less affected by overfiiting problem


In [15]:
from sklearn.datasets import load_iris
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

iris=load_iris()

In [3]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [5]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [6]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [9]:
import pandas as pd
x=pd.DataFrame(data=iris.data)

In [11]:
y=pd.DataFrame(data=iris.target)

In [14]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=.30,random_state=42)

In [16]:
rf=RandomForestClassifier(n_estimators=100,random_state=12)
rf.fit(xtrain,ytrain)
pred=rf.predict(xtest)

C:\Python 2\lib\site-packages\ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  


In [18]:
print(accuracy_score(ytest,pred))
print(confusion_matrix(ytest,pred))
print(classification_report(ytest,pred))

1.0
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



In [19]:
from sklearn.ensemble import AdaBoostClassifier
##AdaBoostclassifier(base_estimator=DecisionTreeClassifier(),n_estimators=50,learning_rate=1.0)
##base_estimator by default decisiontreeclassifier, default learning_rate=1.0 and default n_estimators=50)
ad=AdaBoostClassifier()
ad.fit(xtrain,ytrain)
pred=rf.predict(xtest)
print(accuracy_score(ytest,pred))
print(confusion_matrix(ytest,pred))
print(classification_report(ytest,pred))

C:\Python 2\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


1.0
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



In [22]:
ad=AdaBoostClassifier(n_estimators=50)
ad.fit(xtrain,ytrain)
pred=rf.predict(xtest)
print(accuracy_score(ytest,pred))
print(confusion_matrix(ytest,pred))
print(classification_report(ytest,pred))

1.0
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



C:\Python 2\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


In [24]:
from sklearn.svm import SVC
svc=SVC()
ad=AdaBoostClassifier(base_estimator=svc,n_estimators=50,algorithm="SAMME")
ad.fit(xtrain,ytrain)
pred=rf.predict(xtest)
print(accuracy_score(ytest,pred))
print(confusion_matrix(ytest,pred))
print(classification_report(ytest,pred))

C:\Python 2\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


1.0
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



In [27]:
##algorithm two type "SAMME" and "SAMME.R"
##so by default "SAMME.R"...with decisiontreeclassifier as default base stimator
## if we use SVC() as base estimator..then we need to change algorith as "SAMME" otherwise we will get warning
##in backend "SAMME.R" do not support SVC() becoz by default kernel is "rbf"
##"rbf do not support "SAMME.R" so we will get warnings
##"linear" kernel is comfortable with "SAMME.R"

svc=SVC(probability=True,kernel="linear")
ad=AdaBoostClassifier(n_estimators=50,base_estimator=svc,algorithm="SAMME.R")
ad.fit(xtrain,ytrain)
pred=ad.predict(xtest)
print(accuracy_score(ytest,pred))
print(confusion_matrix(ytest,pred))
print(classification_report(ytest,pred))


C:\Python 2\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


1.0
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



In [28]:
##Hyperparameter Tuning..(random_state)
##or we have criterion in DecisionTreeClassifier(criterion=)
##criterion can be "gini" or "entropy"
##this criterion is hyperparameter
##so we have hyperparameter tuning technique called GridSerchcv
##GridSearch(estimator=,param,cv=)
##param is parametergrid in form of dictionary
##param_grid={"criterion":["gini","entropy"]}
##dtc=DecisionTreeClassifier()
##gd=GridSearchCv(estimator=dtc,param=param_grid,cv=5)
##gd.fit(xtrain,ytrain)
##gd.best_score_
##gd.beat_params_

##so gridsearch with check hyperparameter sequentially first  gini and entropy
##suppose we idnetified which parameter is better then we use that parameter
##dtc=DecisionTreeClassifier(criterion="entropy")
##dtc.fit(xtrain,ytrain)
##pred=dtc.predict(xtest)
##print(accuracy_score(ytest,pred))
##print(confusion_matrix(ytest,pred))
##print(classification_report(ytest,pred))

In [29]:
##Suppose in supportvectorclassifier svc we have kernel=["rbf","linear","poly"]
##svc=SVC()
##param_grid={"kernel":["rbf","linear","poly"]}
##gd=GridSearchCv(estimator=svc,param=param_grid,cv=5)
##gd.fit(xtrain,ytrain)
##gd.best_score_
##gd.beat_params_

In [48]:
from sklearn.datasets import load_breast_cancer
from sklearn.linear_model import Ridge
from sklearn.model_selection import GridSearchCV
import numpy as np
cancer=load_breast_cancer()
x=pd.DataFrame(data=cancer.data)
y=pd.DataFrame(data=cancer.target)




In [47]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=.30,random_state=42)
alphavalue={"alpha":[1,0.1,0.01,0.001,.0001,0]}
model=Ridge()
grid=GridSearchCV(estimator=model,param_grid=alphavalue)
grid.fit(xtrain,ytrain)

GridSearchCV(estimator=Ridge(),
             param_grid={'alpha': [1, 0.1, 0.01, 0.001, 0.0001, 0]})

In [49]:

print(grid.best_score_)
print(grid.best_params_)
print(grid.best_estimator_.alpha)

0.6875815189613158
{'alpha': 0.01}
0.01


In [52]:
all={"alpha":[1,0.1,.01,.001,.0001,0]}
grid=GridSearchCV(estimator=model,param_grid=all)
grid.fit(xtrain,ytrain)
print(grid.best_score_)
print(grid.best_estimator_.alpha)
print(grid.best_params_)

0.6875815189613158
0.01
{'alpha': 0.01}


In [55]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

dtc=DecisionTreeClassifier()
para={"criterion":["gini","entropy"]}

In [59]:
grid=GridSearchCV(estimator=dtc,param_grid=para,scoring="accuracy",cv=5)
grid.fit(xtrain,ytrain)
print(grid.best_score_)
print(grid.best_estimator_.criterion)
print(grid.best_params_)

0.929620253164557
entropy
{'criterion': 'entropy'}


In [60]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [61]:
x=pd.DataFrame(data=iris.data)


In [62]:
y=pd.DataFrame(data=iris.target)

In [69]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=.30,random_state=42)


In [73]:
svc=SVC()
all={"kernel":["rbf","linear","poly"],"C":[1,10]}
grid=GridSearchCV(estimator=svc,param_grid=all)
grid.fit(xtrain,ytrain)
print(grid.best_score_)
print(grid.best_estimator_.kernel)
print(grid.best_params_)

C:\Python 2\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\Python 2\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\Python 2\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\Python 2\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\Python 2\lib\

0.9714285714285715
poly
{'C': 1, 'kernel': 'poly'}


C:\Python 2\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\Python 2\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


In [75]:
print(grid.cv_results_.keys())

dict_keys(['mean_fit_time', 'std_fit_time', 'mean_score_time', 'std_score_time', 'param_C', 'param_kernel', 'params', 'split0_test_score', 'split1_test_score', 'split2_test_score', 'split3_test_score', 'split4_test_score', 'mean_test_score', 'std_test_score', 'rank_test_score'])
