In [1]:
import tensorflow as tf

C:\Users\priya\anaconda3\envs\tf1\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\priya\anaconda3\envs\tf1\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\priya\anaconda3\envs\tf1\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\priya\anaconda3\envs\tf1\lib\site-packages\tensorflow\python\framework

In [2]:
tf.__version__

'1.14.0'

In [3]:
#con is graph and we run it in session
con=tf.constant('hello world')

con

<tf.Tensor 'Const:0' shape=() dtype=string>

In [4]:
with tf.Session() as sess:
    output=sess.run(con)
    print(output)

b'hello world'


In [5]:
s="test"
s

'test'

In [6]:
#A is a 0-dimensional int32 tensor
A=tf.constant(1234)

#B is a 1-dimensional int32 tensor
B=tf.constant([123,456,789])

#C is a 2-dimensional int32 tensor
C=tf.constant([[123,456,789],[987,654,321]])

In [7]:
with tf.Graph().as_default():
    c1=tf.constant(4,dtype=tf.float64,name="c")
    c2=tf.constant(4,dtype=tf.int32,name="c")
print(c1.name)

c:0


In [8]:
print(c2.name)
#as name is similar for c1 and c2 so first time c:0 and second time we c_1:0..1 teling about repetation

c_1:0


In [9]:
with tf.Graph().as_default():
    c1=tf.constant(4,dtype=tf.float64,name='c')
with tf.name_scope("prefix_name"):
    c2=tf.constant(4,dtype=tf.int32,name="c")
    c3=tf.constant(4,dtype=tf.float64,name="c")
    
print(c1.name)
print(c2.name)
print(c3.name)


#name_scope normally group all the values inside particular group together..by name prefix_name

c:0
prefix_name/c:0
prefix_name/c_1:0


In [10]:
C=tf.constant([[123,456,789],[222,333,444]])
sess=tf.Session()
sess.run(C)

array([[123, 456, 789],
       [222, 333, 444]])

In [11]:
#Graph is anything that has nodes and edges..here in tendorflow operations represent the node and data being passed represent 
#the edges
#the nodes or operation are known as op function in tensorflow


In [12]:
init_val=tf.random_normal((1,5),0,1)
var=tf.Variable(init_val,name='var')
print("pre run: \n{}".format(var))
init=tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    post_var=sess.run(var)
print("post run: \n{}".format(post_var))
    

pre run: 
<tf.Variable 'var:0' shape=(1, 5) dtype=float32_ref>
post run: 
[[-0.55923957  0.6347584   0.50710994 -0.3458903   0.10109371]]


In [13]:
#global varibales initializer it stores some memory in session so that we can change the value ..cache it and run it
#every time we run we get random value for the post var as value of var changes due to random_normal
#if we want to reuse the same varibale then tf.get_variables() function is used instead of tf.Variable()

In [14]:
#tf.placeholder()
#this is where we would feed the data
#tf.placeholder() returns a tensor that gets its value from data passed to the tf.session.run() function,allowing you to set the
#input right before the session runs.

x=tf.placeholder(tf.string)

with tf.Session() as sess:
    output=sess.run(x,feed_dict={x:"test"})
    print(output)
    


test


In [15]:
x=tf.placeholder(tf.string)
y=tf.placeholder(tf.int32)
z=tf.placeholder(tf.float32)

with tf.Session() as sess:
    output_x=sess.run(x,feed_dict={x:"Test String",y:123,z:45.67})
    output_y=sess.run(y,feed_dict={x:"Test String",y:123,z:45.67})
    print(output_x)
    print(output_y)
    
#even if we are feeding everything we are getting x and y as output..which we have mentioned before feed_dict

Test String
123


In [16]:
x=tf.placeholder("float",None)
y=x ** 2
with tf.Session() as session:
    result=session.run(y, feed_dict={x: [1,2,3]})
print(result)
#error because data passed to feed_dict doesn't match the tensor type and can't be cast into the tensor type,you wil get the error


[1. 4. 9.]


In [17]:
#tensorflow Math
#..add here is an op function
x=tf.add(5,2)
with tf.Session() as sess:
    re=sess.run(x)
    print(re)
    

7


In [18]:
x=tf.subtract(15,2)
y=tf.multiply(15,2)
with tf.Session() as sess:
    re1=sess.run(x)
    re2=sess.run(y)
    print(re1)
    print(re2)

13
30


In [19]:
z=tf.subtract(tf.constant(2.0),tf.constant(1))
with tf.Session() as sess:
    re3=sess.run(z)
    print(re3)
#error becoz one value is float and other is int
#so we use something called tf.cast()

TypeError: Input 'y' of 'Sub' Op has type int32 that does not match type float32 of argument 'x'.

In [ ]:
#we will cast float to int using tf.cast
c=tf.subtract(tf.cast(tf.constant(2.0),tf.int32),tf.constant(1))
with tf.Session() as sess:
    out=sess.run(c)
    print(out)

In [ ]:
x=tf.constant(10)
y=tf.constant(2)
z=tf.subtract(tf.divide(x,y),1)
with tf.Session() as sess:
    re5=sess.run(z)
    print(re5)

In [ ]:
#tensorflow linear fucntion
#tf.truncated_normal()function returns a tensor with random values from a normaldistribution whose magnitude is no more than 2
#standard deviation from the mean
#since weights are already helping prevent the model from getting stuck,you don't need to randomize the bias.Let's use the
#simplest solution setting the bias to 0
n_features=120
n_labels=5
weights=tf.Variable(tf.truncated_normal((n_features,n_labels)))
weights


In [ ]:
n_labels=5
bias=tf.Variable(tf.zeros(n_labels))

In [ ]:
#feed dictionary
#feed is used to tempropary replace the output of an operation with a tenszor value.The parameter feed_dict is used to override
# the tensor values in the graph and it expects a python dictionary object as input.the keys in the dictionary are handles to
#tensor objects that should be overridden while the values can be numbers,strings,lists or Numpy arrays.
#feed_dict is also useful for specifying input values


a=tf.add(2,5)
b=tf.multiply(a,3)

#startup a session using the default graph
sess=tf.Session()

#define the dictionary that says to replace the value of a with 15
replace_dict={a:15}
#run the session passing in "replace-dict" as the value to the feed_dict
output=sess.run(b,feed_dict=replace_dict)
print(output)

In [ ]:
#tensorflow softmax
#We are using tensorflow to build the neural network and  there is a function to calculate softmax
x=tf.nn.softmax([2.0,1.0,0.2])

In [ ]:
def run_2():
    output=None
    logit_data=[19,354,354,45,354,54]
    logits=tf.placeholder(tf.float32)
    
    softmax=tf.nn.softmax(logits)
    
    with tf.Session() as sess:
        output=sess.run(softmax,feed_dict={logits:logit_data})
        
    return output
print(run_2())
#calculate the softmax of the logits

In [ ]:
#Tensorflow Cross entropy
#To create a cross entropy function in Tensorflow,you will need to use 2 functions
#tf.reduce_sum()
#tf.log()
x=tf.reduce_sum([1,2,3,4,5])
#tf,reduce_sum..takes an array of numbers and sums them together.

#Natural log..tf.log take natural log of number
t=tf.log(100.0)


In [21]:
#print the cross entropy using softmax data and one_hot_encod_label
softmax_data=[0.7,0.2,0.1]
one_hot_data=[1.0,0.0,0.0]

softmax=tf.placeholder(tf.float32)
one_hot=tf.placeholder(tf.float32)

# print cross entropy from session

cross_entropy=tf.reduce_sum(tf.multiply(one_hot,tf.log(softmax)))

with tf.Session() as sess:
    output=sess.run(cross_entropy,feed_dict={one_hot:one_hot_data,softmax:softmax_data})
    print(output)
                    

-0.35667497


In [1]:
#MNIST using tensorflow 1
#Tf2 has eager execution which mean it can be executed without Session..can easily be integrated with keras and vice versa..
#offer more flexibility.

In [2]:
#In google colab they used most recent version of tensorflow

In [3]:
#tf1 we have concept of computational graphs which were used to build models
#Nodes n edges..edges r datapoints n nodes were operations.
#We run computational graph in session


In [30]:
from __future__ import print_function

#Import MNIST data
from tensorflow.examples.tutorials.mnist import input_data
mnist=input_data.read_data_sets("/temp/data/",one_hot=True)

import tensorflow as tf

Extracting /temp/data/train-images-idx3-ubyte.gz
Extracting /temp/data/train-labels-idx1-ubyte.gz
Extracting /temp/data/t10k-images-idx3-ubyte.gz
Extracting /temp/data/t10k-labels-idx1-ubyte.gz


In [31]:
#Parameters
learning_rate=0.1
num_steps=500
batch_size=120
display_step=100
#no of steps/display_steps=epoch

In [32]:
#Network Parameters
n_hidden_1= 256 #1st layer number of neurons
n_hidden_2= 256 #2nd layer number of neurons
num_input= 784 #MNIST data input (img shape: 28*28)
num_classes=10 # MNIST total classes (0-9 digits)

#tf Graph input
X=tf.placeholder("float",[None,num_input])
Y=tf.placeholder("float",[None,num_classes])


In [33]:
#Store layers weights and bias
weights = {
    'h1':tf.Variable(tf.random_normal([num_input, n_hidden_1])),
    "h2":tf.Variable(tf.random_normal([n_hidden_1,n_hidden_2])),
    "out":tf.Variable(tf.random_normal([n_hidden_2,num_classes]))
}

bias={
    'b1':tf.Variable(tf.random_normal([n_hidden_1])),
    "b2":tf.Variable(tf.random_normal([n_hidden_2])),
    "out":tf.Variable(tf.random_normal([num_classes]))
}
    


In [34]:
#Create Model
def neural_net(x):
    #Hidden layer fully connected layer with 256 neurons
    layer_1=tf.add(tf.matmul(x,weights['h1']),bias["b1"])
    #Hidden layer fully connected layer with 256 neurons
    layer_2=tf.add(tf.matmul(layer_1,weights["h2"]),bias["b2"])
    #Ouput fully connected layer with a neuron for each class
    out_layer=tf.matmul(layer_2,weights["out"])+bias["out"]
    return out_layer

In [35]:
#Construct model
logits=neural_net(X)

#Define loss and optimizer
loss_op=tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(logits=logits,labels=Y))
optimizer=tf.train.AdamOptimizer(learning_rate=learning_rate)
train_op=optimizer.minimize(loss_op)

#evaluate the model (with test logits, for dropout to be disabled)
correct_pred=tf.equal(tf.argmax(logits,1),tf.argmax(Y,1))
accuracy=tf.reduce_mean(tf.cast(correct_pred,tf.float32))

#initialize  the variables (i.e assign their default value)
init=tf.global_variables_initializer()


In [41]:
with tf.Session() as sess:
    #run the initializer
    sess.run(init)
    
    for step in range(1, num_steps+1):
        batch_x,batch_y=mnist.train.next_batch(batch_size)
        #run optimization op(backprop)
        sess.run(train_op,feed_dict={X:batch_x,Y:batch_y})
        if step%display_step==0 or step==1:
            #calculate the batch loss and accuracy
            loss,acc=sess.run([loss_op,accuracy],feed_dict={X:batch_x, Y:batch_y})
            print("Step " + str(step) + ", minibatch Loss= " + \
                  "{:.4f}".format(loss) + ", Training accuracy= " + \
                  "{:.3f}".format(acc))
            
    print("optimization finished")

    #calculate accuracy to Mnist test image
    print("test accuracy",sess.run(accuracy,feed_dict={X:mnist.test.images,Y:mnist.test.labels}))

Step 1, minibatch Loss= 8554.7080, Training accuracy= 0.483
Step 100, minibatch Loss= 427.5001, Training accuracy= 0.833
Step 200, minibatch Loss= 86.0255, Training accuracy= 0.942
Step 300, minibatch Loss= 143.9464, Training accuracy= 0.908
Step 400, minibatch Loss= 26.5477, Training accuracy= 0.925
Step 500, minibatch Loss= 33.0546, Training accuracy= 0.925
optimization finished
test accuracy 0.8661
